# -*- coding: utf-8 -*-
"""data_pprocess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QDSIK148ZGou4y_in2R2F-dJ2rTCmCUN
"""

import pandas as pd

df=pd.read_excel("/content/ApexPlanet_DataAnalytics_Dataset.xlsx")
print("Rows and columns ")
print(df.shape)

print(df.head)

#misssing values
print("missing values")
print(df.isnull().sum)

#duplicated rowa
print(df.duplicated().sum())

#datatypes
print("Data types")
print(df.dtypes)

print(df.describe)

# missing Age values
df["Age"]=df["Age"].fillna(df["Age"].mean())

#filling missing city values
df["City"]=df["City"].fillna(df["City"].mode()[0])

#Removing the duplicates
df=df.drop_duplicates()
print("cleaning compleated")

#date column
df["Order_Date"]=pd.to_datetime(df["Order_Date"])
#creating nwe columns
df["year"]=df["Order_Date"].dt.year
df["month"]=df["Order_Date"].dt.month_name()
print(df.head())

df.to_excel("cleaned_data.xlsx",index=False)
print("file saved sucessfully")

